### PR TITLE
(feature): Approximate vorticity fields using velocity data. Include …

### PR DESCRIPTION
**Pull request by greinerth**
…github ci/cd stuff and code quality ensuring stuff

Features:
- included modules for computing vorticity given velocity fields (`vorticity.py`, `velocity2vorticity.py`). Vorticity fields are currently missing in the 3dcfd datasets.
- included `noxfile.py` for automatic testing, building of API doc, and code-linting.

Changes:
- updated `pyproject.toml` (hatchling build) and added additional optional dependencies (dev, test)
- bash file cleanup
- cleanup of python code that can be done without domain-specific knowledge

CICD:
- included `.pre-commit-config.yaml` to ensure code quality in the pipeline and locally
- included github workflows (`precommit.yml`, `python-package.yml`, `python-publish.yml`)
- included "tests" folder with `test_vorticity.py` for future unit testing with pytest.

Help required:
- The employed linters (ruff, pylint) complain a great deal: Unused variables, missing typedefs for input/output parameters etc. The types are mostly unknown and are hard to infer. Thus the pipeline definitely fails.
- Packages: Some of the packages got updates (e.g. jax). This needs to be tested before everything can be updated.
- Extend python support (Python3.11 Python3.12)

### CODE REVIEW

**Comment by kmario23** [comment]
Hey @greinerth, appreciate the PR!  Can you please have a look at the recent commits and resolve conflicts?

**Comment by greinerth** [comment]
> Hey @greinerth, appreciate the PR! Can you please have a look at the recent commits and resolve conflicts?

I'll have a look and resolve the conflicts within the next days.

Cheers,
Gerhard

**Comment by greinerth** [comment]
Done ;)

**Comment by kmario23** [comment]
@greinerth I've had time to look into it. There are issues with relative imports of `vorticity.compute_spectral_vorticity_jnp` in `data_gen/velocity2vorticity.py`. `vorticity.py` should be in the same tree level, which is now in `src`. 

As it exists now, it's postprocessing. So, perhaps we can move these modules to a directory, say `postprocess` in `data_gen`. And, also add some info about how to run this script. E.g.,

```
export PYTHONPATH="/path/to/PDEBench"
CUDA_VISIBLE_DEVICES="0" python -m data_gen.velocity2vorticity --data /pdebench_data/3D/Train/3D_CFD_Turb_M1.0_Eta1e-08_Zeta1e-08_periodic_Train.hdf5
```

Later, we could try integrating this as part of the JAX solver itself and serialize both fields.

**Comment by greinerth** [comment]
Hi @kmario23, good catch! The relative import issue is now fixed.
The conversion is now added as an executable script (c.f. pyproject.toml)
After installing pdebench via pip it can now be executed as follows:
```
velocity2vorticity --data /pdebench_data/3D/Train/3D_CFD_Turb_M1.0_Eta1e-08_Zeta1e-08_periodic_Train.hdf5
```

**Comment by kmario23** [comment]
@greinerth LGTM.

**Comment by kmario23** [comment]
Hey @greinerth, I had a few hours today, and I tried merging the PR and fixing some Ruff linter errors, but there's still a lot to fix. We especially need to add type annotations. I'll ask the authors about this.

It seems the `noxfile.py` is missing. Can you add that in the meantime, please?

**Comment by greinerth** [comment]
I am currently out of office. I'll add it asap (next thursday).

Cheers,
Gerhard

**Comment by kmario23** [comment]
Perhaps we should consider using a logger (e.g., python's `logging`) since Ruff complains about the `print()` statements.

**Pull request merged**
