### PR TITLE
Fixed downloads from Dataverse not working

### PR DESCRIPTION
**Pull request by JR-1991**
This pull request integrates EasyDataverse to download files from a given dataset. Beforehand a mixture of pyDataverse and EasyDataverse was used, but since the latter is based on the former, the code can be reduced accordingly. The current code fetches a dataset from Dataverse and downloads files that match the ```filenames``` entries to the specified directory.

Please note that I have used the development version of [EasyDataverse](https://github.com/gdcc/easyDataverse), which supports the download of specific files, as it was done in your code.

### CODE REVIEW

**Comment by rejuvyesh** [comment]
Have you confirmed that this works?

I get:
```
 File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
    
  File "pydantic/decorator.py", line 201, in pydantic.decorator.ValidatedFunction.execute
    Fix args and kwargs to be consistent with the signature
  File "/home/jagupt/local/anaconda/envs/pdearena/lib/python3.8/site-packages/easyDataverse/core/dataset.py", line 403, in from_dataverse_doi
    return cls._fetch_without_lib(
  File "/home/jagupt/local/anaconda/envs/pdearena/lib/python3.8/site-packages/easyDataverse/core/dataset.py", line 454, in _fetch_without_lib
    return download_from_dataverse_without_lib(**kwargs)
  File "/home/jagupt/local/anaconda/envs/pdearena/lib/python3.8/site-packages/easyDataverse/tools/downloader/downloader.py", line 99, in download_from_dataverse_without_lib
    blocks = [
  File "/home/jagupt/local/anaconda/envs/pdearena/lib/python3.8/site-packages/easyDataverse/tools/downloader/downloader.py", line 100, in <listcomp>
    create_block_definitions(block_name, block, dataverse_url)
  File "/home/jagupt/local/anaconda/envs/pdearena/lib/python3.8/site-packages/easyDataverse/tools/downloader/nolibutils.py", line 95, in create_block_definitions
    block_cls = create_model(
  File "pydantic/main.py", line 972, in pydantic.main.create_model
  File "pydantic/main.py", line 228, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 528, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 559, in pydantic.fields.ModelField._set_default_and_type
pydantic.errors.ConfigError: unable to infer type for attribute "deposit_date"
```

**Comment by JR-1991** [comment]
Thanks for the feedback! Worked on my site before opening the PR. Can you send me the parameters you've used so I can replicate the error?

**Comment by timothypraditia** [comment]
Hi Jan, I also have similar error message. Here's my input parameters:

`defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
    
args:
    filename: '1D_Advection_Sols_beta0.1.hdf5'
    dataverse_url: 'https://darus.uni-stuttgart.de'
    dataset_id: 'doi:10.18419/darus-2986'
    data_folder: 'data'
`

Could the error originate from package dependency?

**Comment by JR-1991** [comment]
Thanks for providing the input arguments! I was able to replicate the error and just found a bug in EasyDataverse. Got it fixed and the download works now on my side. Can you try it now with the new dev version of EasyDataverse?

**Comment by timothypraditia** [comment]
Many thanks Jan for the quick solution!
I have implemented my changes in the main branch now, including matching all filenames that contain a given keyword.

Jayesh: could you try if it works now with the latest version of easyDataverse?

**Comment by rejuvyesh** [comment]
Yep, it works now! Thank you!

**Comment by rejuvyesh** [comment]
Note that the progress bar is incorrect though @timothypraditia!

**Comment by timothypraditia** [comment]
Great to know that it works for you too!
The progress bar is originally defined in the easyDataverse package to indicate going through the whole dataset but downloading only the matching ones.
While it's not urgent, maybe it's worth taking a look Jan?

**Comment by JR-1991** [comment]
Ah that's true, the progress bar iterates over all files although just a fraction is defined. Will look into this for easyDataverse :-)

**Pull request closed without merging**
